// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/xichan96/cortex-lab/internal/app/agent"
	"github.com/xichan96/cortex-lab/internal/app/chat"
	"github.com/xichan96/cortex-lab/internal/app/experience"
	"github.com/xichan96/cortex-lab/internal/app/role"
	"github.com/xichan96/cortex-lab/internal/app/setting"
	"github.com/xichan96/cortex-lab/internal/app/user"
	"github.com/xichan96/cortex-lab/internal/infra/persist"
)

// Injectors from wire.go:

func NewUserApp() user.AppIer {
	userPersistIer := persist.NewUserPersist()
	appIer := user.NewApp(userPersistIer)
	return appIer
}

func NewRoleApp() role.AppIer {
	rolePersistIer := persist.NewRolePersist()
	appIer := role.NewApp(rolePersistIer)
	return appIer
}

func NewExperienceApp() experience.AppIer {
	experiencePersistIer := persist.NewExperiencePersist()
	roleExperienceRelationPersistIer := persist.NewRoleExperienceRelationPersist()
	appIer := experience.NewApp(experiencePersistIer, roleExperienceRelationPersistIer)
	return appIer
}

func NewSettingApp() setting.AppIer {
	settingPersistIer := persist.NewSettingPersist()
	appIer := setting.NewApp(settingPersistIer)
	return appIer
}

func NewAgentApp() agent.AppIer {
	settingPersistIer := persist.NewSettingPersist()
	appIer := setting.NewApp(settingPersistIer)
	agentAppIer := agent.NewApp(appIer)
	return agentAppIer
}

func NewChatApp() chat.AppIer {
	chatSessionPersistIer := persist.NewChatSessionPersist()
	chatMessagePersistIer := persist.NewChatMessagePersist()
	appIer := NewRoleApp()
	settingAppIer := NewSettingApp()
	experienceAppIer := NewExperienceApp()
	chatAppIer := chat.NewApp(chatSessionPersistIer, chatMessagePersistIer, appIer, settingAppIer, experienceAppIer)
	return chatAppIer
}

// wire.go:

var UserAppSet = wire.NewSet(persist.NewUserPersist)

var UserApp = NewUserApp()

var RoleAppSet = wire.NewSet(persist.NewRolePersist)

var RoleApp = NewRoleApp()

var ExperienceAppSet = wire.NewSet(persist.NewExperiencePersist, persist.NewRoleExperienceRelationPersist)

var ExperienceApp = NewExperienceApp()

var SettingAppSet = wire.NewSet(persist.NewSettingPersist)

var SettingApp = NewSettingApp()

var AgentAppSet = wire.NewSet(
	SettingAppSet, setting.NewApp,
)

var AgentApp = NewAgentApp()

var ChatAppSet = wire.NewSet(persist.NewChatSessionPersist, persist.NewChatMessagePersist, NewRoleApp,
	NewSettingApp,
	NewExperienceApp, chat.NewApp,
)

var ChatApp = NewChatApp()
